### ISSUE TITLE
Does this support multiple IDEs?

### ISSUE THREAD

**Issue by Beryesa** [realmazharhussain/nautilus-code#10]
So idk if this was the intended use but I have vscode (native) and builder (flatpak), But it only shows vscode, which makes me think that, it either doesn't support multiple IDEs or there's a bug with the flatpak support. Thanks in advance!

**Comment by realmazharhussain** [comment]
It does support Flatpak.

I need more info to figure out what is going on. Please, provide some system information e.g. OS, OS version, Desktop Environment or Window Manager name, Nautilus version, etc.

Also tell me which branch of builder is installed on the system (stable, beta, nightly, etc.)?

**Comment by 04ELY** [comment]
Fedora 37, Gnome 43.1, Nautilus 43.0, Builder 43.3 stable (flatpak user installation)

**Comment by realmazharhussain** [comment]
Uninstall the previous version and install the latest development version (instructions [here](https://github.com/realmazharhussain/nautilus-code#manual-installation)) and see if it fixes your problem.
