### ISSUE TITLE
Add to Open Menu (GNOME 42 and up)

### ISSUE THREAD

**Issue by KorbsStudio** [realmazharhussain/nautilus-code#12]
![image](https://user-images.githubusercontent.com/51213244/218529908-16482981-ece8-40a9-99ac-bc3c3132cf72.png)

I'm using Nautilus 43.2, which includes a open menu that I'm use to navigating to when I need to open a folder in GNOME Console. I would like to see "Open in EDITOR" here.

**Comment by realmazharhussain** [comment]
I don't think Nautilus supports that.

Everything in this menu including 'Open in Console' item is provided by Nautilus itself and as far as I know this menu cannot be extended by extensions.

**Comment by realmazharhussain** [comment]
I don't think Nautilus supports that.

Everything in this menu (including 'Open in Console' item) is provided by Nautilus itself and as far as I know this menu cannot be extended by extensions.
