### ISSUE TITLE
How to remove old installation?

### ISSUE THREAD

**Issue by marc0x1** [realmazharhussain/nautilus-code#25]
I have reinstalled the extension because I couldn't find the old one.

Now i have some entry duplicated:
- Open in VSCodium
- Open in Builder
- Apri in VSCodium
- Apri in Builder

`.local/share/nautilus-python/ `and` /usr/share/nautilus-python` were empty

**Comment by realmazharhussain** [comment]
The old veesion was written in C. So, it will be in `/usr/lib/nautilus/extensions-4/`.

**Comment by realmazharhussain** [comment]
Also, issues are for actionable stuff like features and bugs. We have [discussions](https://github.com/realmazharhussain/nautilus-code/discussions) enabled for actual discussion.
