### ISSUE TITLE
Add support for Jetbrains IDEs installed via Jetbrains Toolbox

### ISSUE THREAD

**Issue by gurbaaz19** [realmazharhussain/nautilus-code#27]
### Acknowledgements

- [X] I have read the list of [currently supported code editors and IDEs](https://github.com/realmazharhussain/nautilus-code#currently-supported) and I don't see it listed there.

**Comment by realmazharhussain** [comment]
This is the exact same feature request as #9 which was resolved in #23.

If you installed Jetbrains Toolbox just now, you may need reboot or re-login for Jetbrains IDEs to show up in the right click menu.
