### ISSUE TITLE
Rename some "Open in ####"

### ISSUE THREAD

**Issue by Nathan-MV** [realmazharhussain/nautilus-code#5]
### Description

Rename "Open in ####" instances where is used Code-OSS, VSCode, VSCodium and if there is support in the future VSCodeInsiders to "Open in Code" like in Windows.

**Comment by realmazharhussain** [comment]
I do not understand what you are trying to say. Can you explain, please?

**Comment by Nathan-MV** [comment]
In Windows 10 is only Open in Code not Open in VSCode(or any other thing)

**Comment by realmazharhussain** [comment]
> What do you think of:
> 
> > Open in Code
> > Open in Code(Codium)
> > Open in Code(OSS)
> > Open in Code(Insiders)

What if someone installs any of them as a flatpak too along with the native installation? Then flatpaks will be represented as

```
Open in Code (flatpak)
Open in Code(Codium) (flatpak)
Open in Code(OSS) (flatpak)
Open in Code(Insiders) (flatpak)
```

And I do not like it.

Basically, I like the old way and I am not willing to change it.
