### ISSUE TITLE
Support for Desktop

### ISSUE THREAD

**Issue by Nathan-MV** [realmazharhussain/nautilus-code#6]
### Description

Would be nice if there's support to "Open in ####" in the Desktop.
This extension is a very good one btw.
https://extensions.gnome.org/extension/2087/desktop-icons-ng-ding/

**Comment by realmazharhussain** [comment]
This is just a nautilus extension. It cannot change how other extensions (namely DING) behave. You may have to ask the developer of DING for this feature.
